version: '2'
services:
    peaks-app:
        image: peaks
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://peaks-postgresql:5432/peaks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=peaks-elasticsearch:9300
        ports:
            - 8080:8080
    peaks-postgresql:
        extends:
            file: postgresql.yml
            service: peaks-postgresql
    peaks-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: peaks-elasticsearch
